## Basic Configuration
title = "Moien Tajik's Blog | وبلاگ معین تاجیک"
baseURL = "/"
languageCode = "fa"
paginate = 10

## Hugo Built-in Features
disqusShortname = "moientajik"
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  about="Moien Tajik is a software developer with more than 5 years of experience in developing applications."
  themeColor="theme-base-te"
  author = "Moien Tajik"
  authorPersian="معین تاجیک"
  description = "توسعه دهنده نرم افزار"
  authorimage = "/img/Moien Tajik.png"
  dateformat = "01/02/2006"
  highlightjs = true
  highlightjsstyle = "atom-one-dark"
  rtl=true
  
## Social Accounts
[params.social]
  twitter="MoienTajik"
  github="MoienTajik"
  linkedin="MoienTajik"
  stackoverflow="moientajik"
  email = "moientajik@hotmail.com"
  keybase="moientajik"
  medium="MoienTajik"
  
## Main Menu
[[menu.main]]
    name = "خانه"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "مقالات"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "تگ ها"
    weight = 300
    identifier = "tags"
    url = "/tags/"